---
title: "Campaign Memo"
format:
    html: default
    pdf: 
      documentclass: article
      fontsize: 11pt
      colorlinks: true
      citecolor: DarkOrchid
      linkcolor: DarkOrchid
      urlcolor: DarkOrchid
      geometry: margin=1in
      subtitle: | 
        | POL 102 - Introduction to American Politics \vspace{1em}
        | Professor Enrique Quezada-Llanes \vspace{-3em}
---

:::{.callout-important}
## Deadline

Final Draft Due May 2 at 11:59 pm on Canvas.

:::



## Purpose

This assignment will help you think critically about the strategies of members of Congress to win reelection. In doing so, you will practice identifying key pieces of information to inform campaign strategy.


## Task

Write a campaign strategy memo (3-5 pages, single-spaced) for a member of the House of Representatives. Since there is an upcoming election, you will write the memo as if you were part of a real campaign for a real candidate who will be running in the November 2024 election. Pick a member of Congress and write a memo covering the demographics of the member's constituency, the roll call record of the member, and the topics the campaign should focus on.

Make sure to provide clear takeaways for your candidate and campaign. Think about three things you want the staff to remember and be able to execute. The information and analysis you present support those conclusions.


## Criteria for success

A successful essay will:

1. Describe the characteristics of the constituency and identify your electoral coalition.
2. Provide an analysis of the potential for mobilizing your electoral coalition and how you would do this.
3. Clearly define three takeaways for the campaign about how to reach out to voters.
4. Have a coherent structure (paragraphs and headers are your friends here) and no grammatical errors.^[I recommend you use software like Grammarly to have one less thing to worry about.]
5. Cite your sources using hyperlinks. 

Cite academic work in an appropriate tone for the audience. For example, I recommend not using the article's title or even mentioning the authors in the text. Instead, just say "researchers," "scholars," "political scientists," "sociologists," or use any other general terms, and link to the source. 



## Resources

Here are some examples of campaign and political memos. These address various groups a campaign might target so it will be useful to look at them again. Use these examples to understand the genre and see how they are structured. Consider the following: What is important in these pieces of writing? How are those goals reflected in how the text is organized? How is it reflected in the tone of the piece?

- [Memo for 2024 Trump campaign](https://cdn.nucleusfiles.com/f1/f1478561-1972-4c82-945f-e3afb0ddb38f/11.4-memo.pdf)
- [Another 2024 Trump campaign memo](https://cdn.nucleusfiles.com/ad/ad9fb892-dfbd-4284-ac55-fc0c234456f5/10.31-memo.pdf)
- [DCCC memo on abortion ballot initiatives](https://dccc.org/wp-content/uploads/2024/04/4.5.2024-Memo-Abortion-Ballot-Initiatives.pdf)
- [Biden campaign memo example](https://www.wispolitics.com/2020/biden-campaign-memo)
- [Buttigieg campaign memo example](https://www.documentcloud.org/documents/6785938-Path-to-Nomination.html)
- [DeSantis memo](https://s3.documentcloud.org/documents/23874013/0051_001.pdf)


- [Student campaign memo example](https://agnesscott.instructure.com/files/670875/download?download_frd=1)
