---
title: "Assignments"
---

In this course, you will write a campaign strategy memo and an op-ed. In addition, you will also build a concept map that helps you organize and connect the material we will cover in class. You can find more information about each assignment below and in their respective pages.


## Campaign Strategy Memo (40% of final grade, over four assignments)

The major assignment in this course will conclude in a campaign memo for a member of the House of Representatives. You will pick a representative and write a campaign strategy memo. This memo should be directed to campaign staff and should include clear actions and sufficient (but not overwhelming) justification. There are four different assignments that will be due throughout the semester: the demographics of the member's constituency, the roll call record of the member, and the topics the campaign should focus on:

1. Congressmember Profile (10%): This 1-2 page, single-spaced, paper should describe the political career (electoral history, roll-call record, bill sponsorship, etc.) of the member of Congress you chose for your campaign memo.

2. Congressional District Profile (10%): This 1-2 page, single-spaced, paper should describe the demographic and political characteristics of the congressional district your member of Congress represents.

3. Full draft for peer review (5%): Using the research you did in the previous two papers, this is the first full draft of the campaign strategy memo (3-5 single-spaced pages) directed at the campaign staff. You will receive and give feedback from/to a peer.

4. Final draft (15%): This is the final draft of your campaign strategy memo (3-5 single-spaced pages) where you should incorporate the feedback you received on your previous draft.


## Three Response Papers (10% of final grade each)

Throughout the course, we will talk about the state of American democracy. After each of the major sections of the course (foundations, institutions, and the public) you will return to the question of whether American democracy is fragile or stable. In these short papers (2 double-space pages) you will discuss how the different foundations, institutions, or players in American politics contribute to the resilience or erosion of democracy in the United States.

