---
title: "Midterm Exam Guide"
---


This is a list of concepts and frameworks with which you should be familiar for the midterm exam. You might be asked to define and/or apply any of these during the examination. You might not be directly asked about these terms, but they can help you answer some of the questions.



1. Collective Action
    - Why and when is it needed?
    - Problems of collective action
    - Solutions to collective action problems
2. What is politics?
3. Characteristics of democracy
4. Levitsky and Zibblat's take on American democracy
    - Norms for democratic stability
    - The banality of democracy
    - Strategies of authoritarian governments (Chapter 2)
    - In a democracy, what are parties supposed to do when they lose an election?
    - Counter-majoritarian institutions (Chapter 5)
5. Collective Action among the 13 colonies
6. What collective action problems did the states face under the Articles of Confederation?
7. The U.S. Constitution
    - Influences
    - American constitutional system as a product of compromise
8. Federalism
    - How does it compare to a unitary system and a confederation?
    - Dual vs. Shared federalism in the U.S.
    - Evolution of American federalism
9. Civil Liberties
    - Be familiar with a few of them
    - Incorporation
10. Civil Rights
    - Reconstruction Amendments
    - Civil Rights Movement and the role of the Black Church
11. Congress
    - Apportionment of seats to the states
    - Electoral system
    - Behavior of legislators
    - The committee system
    - Mechanisms of party control
    - The median legislator

